### ISSUE TITLE
 Разработка архитектуры приложения

### ISSUE THREAD

**Issue by Quattro9801** [Quattro9801/FitnessProject#1]
Приложение будет представлять собой Fullstack приложение для мобильных устройств.
Для написания приложения будут использованы следующие инструменты:
Spring Boot, JPA/Hibernate, PostgreSQL -backend
ReactNative -frontend

**Comment by rushanrr** [comment]
Добавить схему компонентов и их взаимодействие

**Comment by Quattro9801** [comment]
https://online.visual-paradigm.com/share.jsp?id=313434373032372d31

**Comment by Quattro9801** [comment]
Сделано ссылка в предыдущем сообщении
