### ISSUE TITLE
Page "Authorizations"

### ISSUE THREAD

**Issue by Quattro9801** [Quattro9801/FitnessProject#13]

**Comment by rushanrr** [comment]
Additional info:
https://docs.spring.io/spring-security/site/docs/3.2.0.RC2/reference/htmlsingle/#getting-started
https://spring.io/blog/2013/07/03/spring-security-java-config-preview-web-security/

**Comment by Quattro9801** [comment]
Написана серверная часть https://github.com/Quattro9801/FitnessProject/tree/JwtAuthorization

**Comment by Quattro9801** [comment]
https://github.com/Quattro9801/FitnessProject/tree/main/ReactNativeApp
https://github.com/Quattro9801/FitnessProject/tree/main/SpringBootApp/spring_BD_classic_model
Регистрация и авторизация сделана
