### ISSUE TITLE
Первая часть

### ISSUE THREAD

**Issue by Quattro9801** [Quattro9801/FitnessProject#2]
На данный момент разработана схема базы данных. Она будет представлять собой модель «сущность – атрибут – значение» ( EAV. Данная модель была выбрана, так как она эффективно использует пространство БД. 
https://online.visual-paradigm.com/w/eywyrmkn/app/diagrams/#diagram:workspace=eywyrmkn&proj=0&id=1
После этой части необходимо реализовать доступ к БД из браузера посредством GET и POST запросов.

**Comment by rushanrr** [comment]
Обновить схему БД на внешнем ресурсе.

**Comment by Quattro9801** [comment]
Update
