### ISSUE TITLE
Setup React Native env

### ISSUE THREAD

**Issue by rushanrr** [Quattro9801/FitnessProject#4]
1. Read https://reactnative.dev
2. Create simple app

**Comment by Quattro9801** [comment]
Ready

**Comment by Quattro9801** [comment]
https://github.com/Quattro9801/FitnessProject/tree/HelloWorldReactNative

**Comment by Quattro9801** [comment]
https://github.com/Quattro9801/FitnessProject/tree/HelloWorldReactNative
