### ISSUE TITLE
Add git ignore to project

### ISSUE THREAD

**Issue by rushanrr** [Quattro9801/FitnessProject#7]
Unneeded fileas are added to repository
1) remove .idea and node_modules folders on HelloWorldRecatNative branch
2) remove .idea and target folders on Backend branch

**Comment by Quattro9801** [comment]
Ready

**Comment by rushanrr** [comment]
2. "target" folder is still exist, please check.
3. Remove package-json.lock files as they are auto generated.

**Comment by Quattro9801** [comment]
Added
